name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
<<<<<<< HEAD
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: ubuntu-latest
=======
        container: cuaesd/aesd-autotest:24-assignment5-buildroot
        runs-on: self-hosted
>>>>>>> buildroot-assignments-base/assignment5
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.AESD_SECRET }}
          - name: Run full test
            env:
                GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
